### ISSUE TITLE
'module' fails to parse, if it is a child of param

### ISSUE THREAD

**Issue by c69-addepar** [jsdoc-type-pratt-parser/jsdoc-type-pratt-parser#102]
Recently i have updated to:
```
    "eslint": "^8.2.0",
    "eslint-plugin-jsdoc": "^37.0.3",
    "@typescript-eslint/eslint-plugin": "^5.4.0",
    "@typescript-eslint/parser": "^5.4.0",
```

Several previously valid types started to fail, including the ones with `module` as a property name on argument.

Below is the list of failing and passing cases and the workaround.

____ 

Errors:

```
@param {object} foo
@param {any} foo.module
@param {any} foo.bar.module
```
```
@param {{module: any}} foo
```

Passing:

```
@param {module} foo
@param {foo} module
@returns {module}
```
```
@param {{module}} foo
```
```
@param {{module?}} foo
```

Workaround:
```
/**
 * @typedef {object} Details
 * @property {string} module
 */
 ```

**Comment by brettz9** [comment]
@simonseyock : Any ETA on being able to take a look?

**Comment by simonseyock** [comment]
Hi @brettz9 I am planning to do some work on this repo over the holidays. I probably will look into some more context aware approaches. This might mean that there will be different grammars and therefore options to parse for example `@property` and `@type`. One problem that I see is that `@param` or `@property` contain 2 different parts, the type and the name (i.e. `@property {type} name`). They are parsed independently in `eslint-plugin-jsdoc` but technically they refer to each other, at least superficially. One solution would be to add an extra parse mode for parsing the names as these behave a little different from the types. I will look into that. Do you have an opinion about that?

**Comment by brettz9** [comment]
Yeah, the reason type and name are parsed differently is because of situations like mentioned in https://github.com/jsdoctypeparser/jsdoctypeparser/issues/86 where a type expression such as `Array<string>` should not be allowed in contexts where only a namepath is allowed (e.g., `@typedef {StringArray} Array<string>`). IIRC, types might always support namepaths though (just not the other way around).

As far as parsing the names differently, yes, I think there ought to be a difference, and if possible, yet another one for names as opposed to namepaths.  In `@param` and `@property`, these should only have a name, whereas other tags (like `@namespace`) can have a full namepath, e.g., `abc#instance.staticMethod~etc`. See https://github.com/jsdoctypeparser/jsdoctypeparser/issues/117 for some further background.

**Comment by simonseyock** [comment]
I did not implement different contexts yet, but I moved some step further to make the grammars more modular. The above mentioned types are now parsed.
